name: Bug Report
description: Report a bug or issue with DIGGGIN
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: area
    attributes:
      label: What area is affected?
      options:
        - 3D Rendering / WebGL
        - CSV Data Loading
        - User Interface / Controls
        - Build / Deployment
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen instead
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser and version
      placeholder: "Chrome 118, Firefox 119, Safari 17, etc."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including console errors